version: '3.1'

volumes:
  prometheus1_data: {}
  prometheus2_data: {}
  prometheus3_data: {}
  prometheus4_data: {}
  grafana_data: {}

services:
  prometheus-1:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus1_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus1.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
    ports:
      - 9081:9090
    restart: always

  prometheus-2:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus2_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus2.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
    ports:
      - 9082:9090
    restart: always

  prometheus-3:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus3_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus3.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
    ports:
      - 9083:9090
    restart: always

  prometheus-4:
    image: prom/prometheus:v2.53.1
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus4_data:/prometheus
    command:
      - '--config.file=/etc/prometheus/prometheus4.yaml'
      - '--storage.tsdb.path=/prometheus'
      - '--storage.tsdb.max-block-duration=30m'
      - '--storage.tsdb.min-block-duration=30m'
    ports:
      - 9084:9090
    restart: always

  thanos-sidecar-1:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheus1_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-1:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-1
    restart: always

  thanos-sidecar-2:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheus2_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-2:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-2
    restart: always

  thanos-sidecar-3:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheus3_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-3:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-3
    restart: always

  thanos-sidecar-4:
    image: quay.io/thanos/thanos:v0.31.0
    volumes:
      - ./thanos/:/etc/thanos/
      - prometheus4_data:/prometheus
    command:
      - 'sidecar'
      - '--tsdb.path=/prometheus'
      - '--prometheus.url=http://prometheus-4:9090'
      - '--grpc-address=0.0.0.0:10091'
      - '--http-address=0.0.0.0:10902'
      - '--objstore.config-file=/etc/thanos/bucket_config.yaml'
    depends_on:
      - prometheus-4
    restart: always

  node-exporter:
    image: prom/node-exporter:v1.8.2
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
    ports:
      - 9100:9100
    restart: always

  alertmanager:
    image: prom/alertmanager:v0.27.0
    ports:
      - 9093:9093
    volumes:
      - ./alertmanager/:/etc/alertmanager/
    restart: always
    command:
      - '--config.file=/etc/alertmanager/config.yaml'
      - '--storage.path=/alertmanager'

  grafana:
    image: grafana/grafana:10.4.6
    user: "104"
    depends_on:
        - prometheus-1
        - prometheus-2
    ports:
      - 3000:3000
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    env_file:
      - ./grafana/config.monitoring
    restart: always

  yace:
    image: ghcr.io/nerdswords/yet-another-cloudwatch-exporter:v0.58.0
    volumes:
      - ./cloudwatch-exporter/yace-config.yaml:/config.yaml
    command:
      - "--config.file=/config.yaml"
    ports:
      - "5000:5000"
